### ISSUE TITLE
Remove unnecessary connections to DOIT

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#100]
Most importantly, rename doit_i_field. What did we decide?

Other similar stuff?

Move general functions from doit-files, to e.g. m_cloudbox.

**Comment by olemke** [comment]
I found these bullet points in an email from you titled `Cleaning and extensions of ARTS` from 2017:
```
* Introduce clear variables for intensity fields
> Should we have both i_field and i_field_cloudbox?
> Remove/rename doit_i_field
> Shall we have i_field_za_grid and i_field_aa_grid. Should then replace scat_za/aa_grid?
> These questions TBD
```

**Comment by m-brath** [comment]
If my notes are correct, we decided to rename to doit_i_field to "iy_field", but we postponed the renaming. I don't know if the new name is still valid.

**Comment by erikssonpatrick** [comment]
What I remember, we exchanged some emails with a suggestion on names and methods. But I can not find any of these emails. Freddy, did you take this from any of these emails?

But yes, I think we ended with that suggestion. Shall we reconsider? Shall we call it cloudbox_field? To have a clear distinction to spectral_radiance_field (that does not exist, but could make sense) that should be defined for the full atmosphere. But what do we then do with the angular grids, what names would fit?

Now happened to see that radiance_field and irradiance_field are defined to have size following te cloudbox. Does that not make sense to me. Did we decide that?

**Comment by olemke** [comment]
You mean these?
https://www.mail-archive.com/arts_dev.mi@lists.uni-hamburg.de/msg00114.html

**Comment by erikssonpatrick** [comment]
Yes. Thanks Oliver.

Another sub-thread. We need to introduce a clear definition, for all radiation fields, on how to handle cases when the surface is above the first pressure level. I was going to implement something for the interpolation of doit_i_field, but realised that it is a more general issue.

My suggestion: If the surface would happen to be exactly at e.g. p_grid[2], then the field at levels 0 and 1 are simply undefined. Quite straightforward. But what to do if the surface is between levels 2 and 3?  Here I suggest that the radiation field at the surface is assigned to level 2 (and field at 0 and 1 is undefined). If you later interpolate this field, you have to replace z_field[2] with the surface altitude and all should be OK. (But it should be remembered that the field can be 3D!) 

What do you think? For me, this is the most urgent question because if I get some free time this my next ARTS ToDo.

**Comment by erikssonpatrick** [comment]
Richards comment made remember another thing. We use the term transmission, while we, in fact, mean transmittance. See e.g.
https://en.wikipedia.org/wiki/Transmittance
https://wikidiff.com/transmission/transmittance

In some places, we use trans, as a short name for transmittance. Not a fan of this short version.

Shall we go for transmittance?

**Comment by erikssonpatrick** [comment]
@riclarsson If you now have line_irradiance and line_transmission, are then transmission_field and radiation_field obsolete?

**Comment by riclarsson** [comment]
None of my functions use `radiation_field` or `transmission_field` anymore.  ARTS compiles without it.

**Comment by erikssonpatrick** [comment]
Can we try to reach a decision around trans? I have looked around in textbooks and found three names describing the fraction being transmitted, ie. a value between 0 and 1:
transmission coefficient
transmittance
transmissivity
(no pace found where just transmission being used for this)

See e.g. Wallace and Hobbs, footnote 8 on page 120, for a small discussion.

Considering that we have "reflectivity" (eg. in surface_reflectivity), I now suggest that we go for transmissivity. That is, replace "trans" and "transmission" in WSV and WSM names with "transmissivity".
 
OK?

**Comment by riclarsson** [comment]
Hi Patrick,

I agree with you on the 1D case, transmissivity/transmittance are much
better terms. I have a small problem with it being used for 3D.

By the standard sources (Google and a few links), you're supposed by most
of them to be able to define transmittance/transmissivity as a ratio of two
signals.  This is simply not our formalism since we deal in the differences
of ratios of signals in addition to the main ratio.

I prefer transmission since it is a wider word for the general concept. I
will not complain more than this if you or others go ahead and change the
names though, since all three names are similar enough that it really
doesn't matter. So long as we are consistent throughout the code and the
docs that is.

With hope,
//Richard
