### ISSUE TITLE
Remove lines from continua.cc and put them in AbsorptionLines format?

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#128]
Hi,

The main point of this post is to summarize a conversation I had with @erikssonpatrick about the use of full models via continua.cc in ARTS.  We both encountered problems where the continua.cc solution was sub-optimal because we had to change values.  There is a need to change how these continua are done.

We have many models in continua.cc using line absorption and true continua absorption interchangeably to give full absorption model code.  This comes with several problems and limitations.  Not only is the continua.cc code difficult to follow but some questions about its reliability is also difficult to answer, for example:
1. Does the true continua really match the absorption lines when either lines or continua is updated (we have done this but I don't know if we have checked)?
2. How do we estimate the model errors when everything is hard-coded (we cannot today)?
3. How do we append other absorption lines while making sure we do not accidentally add a line that is in the hard-coded model (we need quantum number encoding)?

The advantage is that at least some of the full models are well-tested and known to work.  They are the 'industry standard', but we do not have clear ways to improve them and to update them to newer models as new papers come out.  The continua.cc code is just too messy and difficult to work with.

I implemented two solutions recently. One was to hard-code an absorption line model external to continua.cc via a method so that all the model parameters' derivatives can be computed and thus their errors understood.  The other is to adopt AbsorptionLines to use the full model's parameters (which already can propagate all the errors).  @erikssonpatrick informed me he has recently done the latter as well for a different project.  The differences between our approaches is that I enforced the same temperature behavior as the full model whereas he manipulated the standard line parameters to match the model.  My solution is, of course, more in line with the intent of the full models, but it comes with the cost of complication.  Essentially, I have introduced a new way to compute the line strength and thus a new way to deal with LTE radiative transfer into our line shape calculations.  We need to allow not just one but many definitions of the line strength for this to work, since the temperature dependency is not clear otherwise.

I am sure one of these three solutions is the way forward for ARTS.  We need to separate the full models - in a method that is easy to document - from the amalgamation of different physics that makes using the true continua models necessary.  Since we want to be able to describe the physics via our own line catalogs, we need to be able to describe these continua in a way that can be matched to the line catalogs.  Any thoughts on how to go forward here?

My personal view is that hard-coded non-continua.cc models are the best way to do this for now.  It is clear what you are doing when you include a model, and it is clear what the individual model is doing.  We then might want to fit these to the ARTS absorption line parameters, or compute our own parameters from the original data, but at least we have the original model to compare towards, and we can then easily allow others to use said model.

**Comment by erikssonpatrick** [comment]
Was decided in some discussion between Stefan, Richard and me that should not be done.
