### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by simonpf** [atmtools/arts#143]
The following test currently fail because they use the obsolete `abs_lineshapeDefine`:

	 80 - arts.ctlfile.nocheck.instruments.hirs.TestHIRS_reference (Failed)
	 82 - arts.ctlfile.nocheck.instruments.seviri.TestSEVIRI (Failed)
	 83 - arts.ctlfile.nocheck.instruments.mviri.TestMVIRI (Failed)

**To Reproduce**
Run `ctest`

**Expected behavior**
Tests shouldn't fail

**Comment by simonpf** [comment]
assigned @riclarsson assuming that the changes were introduced with the refactoring of lineshape handling.

**Comment by riclarsson** [comment]
@simonpf These tests are not run by "make check-all".  They should be removed from the test setup entirely. I do not know if they worked up to before the refactoring.  The only thing the refactoring did for the line shape is that the lines

```
abs_linesSetCutoff(abs_lines, "ByLine", 750e9)
abs_linesSetNormalization(abs_lines, "VVH")
```

needs to be added after `abs_lines` has been defined (or their species-specific versions if `abs_lines_per_species` is used).  Of course, the relevant ReadXML or read* line data file has to also be changed to the correct one for AbsorptionLines.

My recommended solution is to remove all "nocheck" checking-commands from relevant CMakeLists.txt file
