### ISSUE TITLE
Raw data in ARTS

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#157]
With the OEM module in place, I think it would be a good idea to have the ability to process raw-data in ARTS to generate lists of `y` and `covmat_se`/`covmat_seps` from some raw-time series.  (The latter does not exist today, since `covmat_se` is defined to contain it.)

Is this an idea accepted by others?  Or do you want to keep rawdata processing out of ARTS still?  I think it fits to have it given the addition of OEM.

My design of this would be very simply in the beginning but could of course evolve if it helps other observation schemes.  An agenda would be created, called `rawdata_agenda`.  This agenda outputs a `ybatch`, an `ArrayOfCovarianceMatrix` `covmat_sepsbatch`, and an `ArrayOfIndex` `ybatch_count`.  It takes only a `Matrix` `rawdata` as input.  The methods inside this agenda could then require more information.

In the original implementation I intend to use this for I have a simple repeating cold-atm-hot-atm measurement cycle.  The method for generating `ybatch` from this would be called `ybatchFromRawdataCAHA` and require an additional `hot` and `cold` temperature `Vector` input.  (Just to keep the start of this simple.)  Additionally, a `TimeAverageBatchCalc` method would be created that takes a `time` `Vector` and a `time_target` `Numeric` to reduce the size of `ybatch` and generate `ybatch_count` and `covmat_sepsbatch` at the correct sizes.

**Comment by erikssonpatrick** [comment]
I have probably some knowledge of the calibration routine of 6-8 radiometers, and they all differ. I have never seen anyone just using single hot and cold measurements to produce spectra. There is always some averaging of hot and cold, at least averaging of the closest two of each. There could also be observation cycles, observing one load more frequently than the other. There could be one or several atmospheric views for each calibration view. For ground-based, a tipping curve procedure could be involved. For satellites, non-linear correction terms could be applied.

So despite it would make sense if ARTS could handle the complete chain from L0 to L2, I just don't think this can be standardised sufficiently to make it fit ARTS without causing confusion in the end.

Is this not something for Python? To make calibration routines for different instruments. Maybe this can be compared to reformat the output of OEM (the x vector) to the L2 format around different sensors. This is again nothing can be standardised and fits better for keeping in Python, Matlab ...

So I take the liberty to close this one.

**Comment by riclarsson** [comment]
I will go ahead and open this issue again because you answer seems to miss somethings Patrick.

Can we agree that ARTS should be able to handle everything from L1 to L2?

We cannot presently do things like compute time averages (e.g., 22 GHz water), "move-the-sensor" (e.g., tropospheric corrections, astronomical stuff), and compute forward model observation uncertainty contributions (i.e., provide `covmat_sb` and `covmat_seps` for `covmat_se`).  There are more things, but at least these three are essential things to go from L1 to L2 for the radiometers I work with.

I don't buy that it is not possible to standardize here as an argument in any way.  L0 to L1 is just a bunch of masked algebraic operations.  But since I have only worked with 2 different designs of front-ends, both ground-.based, I will leave this generalization for now.  I will add an L0 to L1 to compute `y` from maskless `hot`, `cold`, and `atm` data.  I will leave `ybatch` generation to python for the other L1 to L2 routines mentioned above.

I will skip the idea of `rawdata` for now.

**Comment by erikssonpatrick** [comment]
Yes, that are several tricks involved in the retrieval of ground-based data. We have tested quite a bit. And yes, would be nice to have this in ARTS. Maybe my experience could be of help? For example, Ole Martin and I did a study on doing a time series retrieval. Seems easiest is to discuss this by video. A zoom tomorrow (Wed) 10.30?

**Comment by riclarsson** [comment]
Tomorrow or Wednesday?  I can be available either time.

**Comment by erikssonpatrick** [comment]
Sorry. I meant Tue. You should have got a meeting invitation.

**Comment by riclarsson** [comment]
#302 adds a test-case that tests the raw.  This should be enough to close this issue.
