### ISSUE TITLE
Intterpolation weights figure

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#200]
@stefanbuehler As far as I understand, Fig 5.2 (and then also Eq 5.1) does not match the implementation. The weights are stored in another order. For example, the first and last weights are at opposite corners, while the figure places them along one side. 

It would also be good to mark in Fig 5.2 what is the row and column dimension.

If problematic to update the figure, maybe just clarify that the description is schematic.

That said I wished that all parts of ARTS were as well documented as the implementation of tensors and interpolation. 

/P

**Comment by stefanbuehler** [comment]
I have fixed this and made a pull request.
