### ISSUE TITLE
Running ctest -R from commad lne

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#201]
When I run ctest -R from the command line, also the python "version" is launched. Should it work like that? A bit annoying that it ends with a fail when all is OK as far as I am concerned.

Here is an example:

cirrus|build: ctest -R TestAntenna2D
Test project /home/patrick/GIT/ARTS/arts/build
    Start 130: arts.ctlfile.fast.artscomponents.antenna.TestAntenna2D
1/2 Test #130: arts.ctlfile.fast.artscomponents.antenna.TestAntenna2D ..........   Passed    3.20 sec
    Start 131: python.arts.ctlfile.fast.artscomponents.antenna.TestAntenna2D
2/2 Test #131: python.arts.ctlfile.fast.artscomponents.antenna.TestAntenna2D ...***Failed    0.02 sec
/usr/bin/python3: can't open file 'controlfiles/artscomponents/antenna/TestAntenna2D.py': [Errno 2] No such file or directory

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   3.22 sec

The following tests FAILED:
	131 - python.arts.ctlfile.fast.artscomponents.antenna.TestAntenna2D (Failed)
Errors while running CTest

**Comment by olemke** [comment]
`ctest -R STRING` does a simple pattern match of STRING against all test names and thus also matches the python test cases. If you want to ignore the Python cases, use the -E option to exclude them, e.g. `ctest -E python -R ClearSky`

**Comment by riclarsson** [comment]
I think that the tests should either succeed after a simple make, or the tests must be removed from credit. We should treat python as first class, i.e. remove the translated tests OR copy them to the python tests folder. Also, do they even work out of the box when built without first copying over a lot of data?

**Comment by olemke** [comment]
The Python test only failed because Patrick didn't use make to run all tests, but wanted to execute this one test explicitly during development. Eventually, at the latest in the pull request, all tests will be executed. Normal and Python tests. If any test fails, it has to be fixed of course. But I can confirm that all tests passed in his PR #202

**Comment by riclarsson** [comment]
Right, then there is a bug on Ubuntu.  I run in an empty build directory the following commands:

```
cmake ..
make -j21
ctest -R TestDoppler -V
```

And if I should expect it to work as you say, I would not get any errors.  Instead, I get the following output and error:
```
UpdateCTestConfiguration  from :/home/larsson/Work/arts/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/larsson/Work/arts/build/DartConfiguration.tcl
Test project /home/larsson/Work/arts/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 70
    Start 70: arts.ctlfile.fast.artscomponents.lineshapes.TestDoppler

70: Test command: /home/larsson/Work/arts/build/src/arts "-r002" "-I/home/larsson/Work/arts/controlfiles" "-D/home/larsson/Work/arts-xml-data" "/home/larsson/Work/arts/controlfiles/artscomponents/lineshapes/TestDoppler.arts"
70: Test timeout computed to be: 10000000
1/2 Test #70: arts.ctlfile.fast.artscomponents.lineshapes.TestDoppler ..........   Passed    0.07 sec
test 71
    Start 71: python.arts.ctlfile.fast.artscomponents.lineshapes.TestDoppler

71: Test command: /home/larsson/anaconda3/bin/python3 "controlfiles/artscomponents/lineshapes/TestDoppler.py"
71: Environment variables: 
71:  PYTHONPATH=/home/larsson/Work/arts/build/python
71:  ARTS_INCLUDE_PATH=/home/larsson/Work/arts/controlfiles/artscomponents/lineshapes:/home/larsson/Work/arts/controlfiles:/home/larsson/Work/arts-xml-data
71: Test timeout computed to be: 10000000
71: /home/larsson/anaconda3/bin/python3: can't open file 'controlfiles/artscomponents/lineshapes/TestDoppler.py': [Errno 2] No such file or directory
2/2 Test #71: python.arts.ctlfile.fast.artscomponents.lineshapes.TestDoppler ...***Failed    0.02 sec

The following tests passed:
	arts.ctlfile.fast.artscomponents.lineshapes.TestDoppler

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.10 sec

The following tests FAILED:
	 71 - python.arts.ctlfile.fast.artscomponents.lineshapes.TestDoppler (Failed)
Errors while running CTest
```

To find the file, I have to run:
```
make python_tests
```

And then the tests succeed.  Clearly what you are saying, that a normal make will ensure that you have the tests, is not working on Ubuntu.  I would expect ctest to work or CMake to not populate the tests if I choose to not build python_tests.

**Comment by olemke** [comment]
Ok, sorry for confusing you. Yes, you are right, a `make check` is needed to create the python test files.
