### ISSUE TITLE
Remove Old RT code

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#209]
Once DOIT has been updated (#207), a lot of the old RT code becomes obsolete.  I will have a look at removing it.  Please ping me @m-brath when you are done with #207 .

**Comment by m-brath** [comment]
The old DOIT and my new DOIT  are using only one function of rte.{cc,h}. Both use the "get_iy" - function to get the incoming radaition on the cloudbox, which is an interface to *iy_main_agenda* that can be used if only *iy* is of interest. For the case of old DOIT the "get_iy" - function can be moved to doit.{cc,h}. For the case of my new DOIT, I would include this function within my newdoit files.

**Comment by erikssonpatrick** [comment]
This is good news. This is just a small helper function that is independent of the change to the "new RT" system.

Not critical, but it could be considered to remove get_iy and instead call iyCalc.
