### ISSUE TITLE
Name clash between ARTS variable names and numpy

### ISSUE THREAD

**Issue by olemke** [atmtools/arts#249]
**Describe the bug**
After creating an ARTS variable with the name "np", `.value` cannot be called anymore for any variables that map to numpy types.

**To Reproduce**
```python
import pyarts

ws = pyarts.workspace.Workspace()
ws.VectorSetConstant(ws.f_grid, 10, 1.)

print("OUT1: ", ws.f_grid.value)
ws.VectorCreate("np")
print("OUT2: ", ws.f_grid.value)
```

If applicable, error output:
```
OUT1:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Traceback (most recent call last):
  File "test_value.py", line 8, in <module>
    print("OUT2: ", ws.f_grid.value)
  File "/home/olemke/anaconda3/lib/python3.8/site-packages/pyarts/workspace/variables.py", line 357, in value
    return np.asarray(self)
AttributeError: 'WorkspaceVariable' object has no attribute 'asarray'
```

**Expected behavior**
Defining an ARTS Variable with the name "np" should not break access to the `.value` method or the `*Create` methods need to catch illegal names.

**System info (please complete the following information):**
 - OS: Linux/macOS
 - Version 2.5.0

**Comment by simonpf** [comment]
This is actually a feature, not a bug. It is intended to keep people from using obscure WSV names.
