### ISSUE TITLE
iyHybrid or iyHybrid2

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#264]
There is a replacement of iyHybrid using the new interface.  If this is merged as the default, get_diydx in jacobian.h/jacobian.cc can be removed.

I made the interface but @erikssonpatrick  told me he or someone else would setup a test.  I no longer remember the state of this but would like to remove get_diydx since I had a minor look at jacobian.h/cc today.

Anyways, what is the status?  I think a decision needs to be made before ARTS 3.

**Comment by olemke** [comment]
Duplicate of #205

**Comment by erikssonpatrick** [comment]
Yes. Let's close this one.
