### ISSUE TITLE
nlte_field input to iy_main_agenda

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#279]
We may have discussed this ...

Since some time it is only nlte_field of the atmospheric fields that is input to iy_main_eganda. 

Is there a reason to this? Or can it be removed? Would look less striking.

Just asking. Richard if you don't see a reason, I will try to remove it.

**Comment by riclarsson** [comment]
It cannot be removed.

`nlte_field` is a function of the radiation but the radiation is also a function of `nlte_field`.  In the ARTS implementation, you have to compute `iy` for a good guess of `nlte_field`, change `nlte_field` to what it would be if all your understanding of the chemistry and collisions of the atmosphere are correct (i.e., call the `statistical_equilibrium_equation` function or something similar), and then you start all over again.  You have to repeat this until `nlte_field` is no longer changed and you have an answer.

Thus, the first `nlte_field` from workspace does not work when calling the iy-agenda.

**Comment by erikssonpatrick** [comment]
Ok, it rings a bell.

Yes, case closed. I wished all issues were this easy!
