### ISSUE TITLE
Flatten *propmat_clearsky*

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#303]
**Is your enhancement request related to a problem? Please describe.**
The `propmat_clearsky_agenda` outputs an `ArrayOfPropagationMatrix` for `propmat_clearsky`.  Clearly, the physical representation here is that of a simple `PropagationMatrix`.

**Describe the solution you'd like**
Flatten `propmat_clearsky`.

**Describe alternatives you've considered**
I am unsure what to put here.  If we leave it as it is it works.  If we change it so the output is the desired `PropagationMatrix`, then there is no need for a temporary allocation in the step-wise functions dealing with the propagation matrix agenda.  There are still allocations in the agenda, but that's perhaps also possible to fix by letting init only allocate for wrong sizes, and otherwise simply reset.

**Are you willing to help adding this enhancement?**
I will make the change myself so long as I am not missing something.

**Additional context**
I am unsure what else could break by this change.  It is clear that the lookup table calculations would have to change.  This is somewhat trivial, as it does not deal with the Jacobian in the setup.  It is easy therefore to have a mock Jacobian and just feed the mock derivative output into the lookup table.  But what else might break?

I flatten nlte_source in #302, and it was mostly a trivial change.  So I know this can be done quite easily.  Having the propagation matrix output be its actual physical value really would help program flow as well, since it allows a bit less knowledge of the gotchas of ARTS.  It would make it quite easy, for instance, to allow plotting of contribution functions by species using external tools.

**Comment by riclarsson** [comment]
@olemke and @stefanbuehler 

Am I missing something here.  What are you otherwise using the propagation matrix for than the lookup table?

**Comment by stefanbuehler** [comment]
I'm not sure what you mean by flattening. I think the original reason why this is an array is that Jacobians calculation needed the absorption separately for each species.

**Comment by riclarsson** [comment]
@stefanbuehler 

`propmat_clearsky` is an `ArrayOfPropagationMatrix`.  A flat version of it would be simple a `PropagationMatrix`.

It is not too difficult to have the logic that puts the derivatives into their right parts of `dpropmat_clearsky_dx` inside the `propmat_clearsky_agenda`.  That way, you would have a flat `PropagationMatrix` as output.  Quite a lot of code is written to simply flatten the current array outside of the agenda.  I think this is the wrong way to do things.

The main advantages of making the shift is that the output of the propagation matrix agenda is actually a useful propagation matrix.  This means that there is no need for temporary allocations of the array in many places that calls the agenda.  For example, `get_stepwise_clearsky_propmat` would no longer need to allocate `propmat_clearsky` as an array but could use it's `K` input directly.  This is a very central agenda in the RT setups.

**Comment by stefanbuehler** [comment]
Ah, I had missed the dpropmat_clearsky_dx output of 
propmat_clearsky_agenda. If I remember correctly, that did not exist 
when the original design was made, hence the array output.

Ok, your proposed change seems to make sense from my point of view.

**Comment by riclarsson** [comment]
#302 fixed this
