### ISSUE TITLE
Potential bug in yCalcAppend

### ISSUE THREAD

**Issue by simonpf** [atmtools/arts#331]
yCalcAppend stopped working in 2.5 branch for temperature Jacobians. Using it triggers the [following error](https://github.com/atmtools/arts/blob/4448941fb8f988eb07aaf47cc89b7d90863f62d9/src/m_rte.cc#L1824). This obviously fails because the subtag of non-temperature JQs is completely different than for temperature . From looking at it, it seems to me the correct check should be:

```c++
          // Temperature
          else if ((jacobian_quantities2[q2] == Jacobian::Atm::Temperature) &&  
                   (jacobian_quantities_copy[q1] == Jacobian::Atm::Temperature) {
            if (jacobian_quantities2[q2].Subtag() == jacobian_quantities_copy[q1].Subtag()) {
              pos = q1;
              } else {
                ARTS_USER_ERROR (
                  "Jacobians for ", jacobian_quantities2[q2],
                  " shall be appended.\nThis requires "
                  "that HSE is either ON or OFF for both "
                  "parts but it seems that this requirement "
                  "is not met.")
              }
            }

```

**Somebody who has a better understanding of this code please confirm so I can fix this or convince me why this is not a bug.**

 Thanks :)

**Comment by riclarsson** [comment]
In #341 I think I found the bug.  Your solution is correct for temperature.  I just one-upped it by wrapping all targets inside a similar test.  Please check if this works, I don't know the intent of this code and these copies.  Seems weird to me they are done at all, and in such a high level function.

**Comment by olemke** [comment]
Since this basically restores the check to how it was before #182, I think it's good.
