### ISSUE TITLE
Bug with sparse multiplication

### ISSUE THREAD

**Issue by riclarsson** [atmtools/arts#344]
**Describe the bug**
Running ARTS with many frequencies, there's an uncommon bug where a too high a count `f_grid` generates bogus numerical noise in `y`.  I tracked the error down to the multiplication happening in `yCalc_mblock_loop_body` between the internal calculations and the sensor response.  That is the line with the call `mult(yb, sensor_response, iyb);` is causing problems.

Note that my use-case is clearly a sparse case with ones along the entire diagonal.  So this multiplication is completely unnecessary.  If the problem cannot be reproduced and fixed, I will therefore introduce a `sensor_do` parameter that ignores the multiplication when `false`.

**To Reproduce**
It is not clear to me that this is reproducible every time someone runs the code on different platforms with different settings since the bug is numerical.  For me, a reliable way to reproduce the bug is to change between 1'000 and 10'000 frequencies in the attached script:
[test.zip](https://github.com/atmtools/arts/files/6413656/test.zip)

**Expected behavior**
I expect to see something akin to this on the y-axis (x is counts here):
![exp](https://user-images.githubusercontent.com/3504184/116855469-b5c93180-abf9-11eb-80ca-c6a185ae4bea.png)
I get this on the y-axis (x is counts here):
![get](https://user-images.githubusercontent.com/3504184/116855476-b95cb880-abf9-11eb-9a42-37a07b470741.png)
This is clearly numerical noise.  But the shape is mostly intact.  Note that the way this noise looks changes if I run the code again.  This makes it look like I am accessing some memory that is out-of-bounds for the Eigen C-array.

**System info (please complete the following information):**
 - Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.
 - Version: latest dev-branch of ARTS

**Additional context**
I have seen this problem before but didn't have immediate time to report it.  When I've come back to it later, it turns out to be difficult to reproduce.  So I think this really depends on architecture and build options.

**Comment by olemke** [comment]
Ok, after testing 3 different systems and compilers all working fine, I finally found one where I can reliably reproduce this. Incidentally, it is also the only system with GCC version 9. I wonder if that's coincidence. I'll let you know when I find out more.

**Comment by olemke** [comment]
It appears the issue is triggered by OpenMP. With 1 thread, I was not able to produce the artifacts. With 4 threads, they appear sometimes and do so more frequently with higher thread counts. Not sure if this is isolated to GCC 9. It's unfortunately the only compiler version available on the system where I can reproduce the issue. I have to do more tests tomorrow on a different system with higher thread counts.

@riclarsson Can you please let me know if the issue goes away for you as well when you run the test with only one thread? `OMP_NUM_THREADS=1 python zeeman_sim.py`

**Comment by riclarsson** [comment]
@olemke, the problem goes away running with `OMP_NUM_THREADS=1 python zeeman_sim.py`.  According to Eigen docs, I see that we should be defining `EIGEN_DONT_PARALLELIZE` since we are doing our own parallel stuff.  Is this defined?  They say so here: [Using Eigen in a multi-threaded application](https://eigen.tuxfamily.org/dox/TopicMultiThreading.html)

As far as I can see, the sparse multiplication is an Eigen-thing.

(Note though that I am not actually doing anything in parallel at that stage, I've tried to debug this with the GUI plotter and it is just a linear sequence as far as I can see.)

**Comment by olemke** [comment]
@riclarsson  Yep, I came to the same conclusion. :-)
