### ISSUE TITLE
Finish iyActiveSingleScat2

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#41]
Richard: I have created the first version of a test targeting Jacobians by iyActiveSingleScat. Presently it just checks that things run. The test runs with iyActiveSingleScat but crashes with iyActiveSingleScat2. 

The test is called TestIyActive_wfuns.arts

**Comment by riclarsson** [comment]
Note, pull request #46 is not using the naive reflection routine you had implemented for derivatives Patrick.  Instead, it is looking directly at the pure forward equation and defines the derivative from it.  This might be why there are differences.  At this point though, I have done my part of this problem and will unassign myself from further work on this.

**Comment by erikssonpatrick** [comment]
New goal of issue: Check iyActiveSingleScat2 and when done make this iyActiveSingleScat

**Comment by erikssonpatrick** [comment]
Replaced by issue #205
