### ISSUE TITLE
should abs_lines_per_speciesSetEmpty also set Xsec empty?

### ISSUE THREAD

**Issue by j-petersen** [atmtools/arts#413]
`abs_lines_per_speciesSetEmpty` only empties the line data and not the cross section data. Which can be intended behaviour since the name states it empties the abs_lines. 

However, since for star arts we will rely on cross sections, one could consider to also empty them as well and presumably rename the function too.

**Comment by riclarsson** [comment]
`abs_lines_per_species` is its own variable.  This helper function is only there to allow a "no lines" test scenario.  If you want something similar for the cross-sections I think you need a `cross_section_variableSetEmpty` method as well.
