### ISSUE TITLE
Arrange next ARTS workshop

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#42]
A workshop to celebrate the first 20 years. Also ARTS-3?

**Comment by erikssonpatrick** [comment]
Checked with Kristineberg and they strongly recommended week 24 and 25 (June 15-25). June 26 or later do not work.
Checked around and did not find any conflict with conferences, but my search was not extensive.

**Comment by stefanbuehler** [comment]
Both weeks work well for us, as far as I can tell.

**Comment by olemke** [comment]
Dates work for me.

**Comment by erikssonpatrick** [comment]
Kristineberg booked June 8-11

**Comment by erikssonpatrick** [comment]
All done for now. Next step is to send out an invitation in January.
