### ISSUE TITLE
Inconsistent ppath inline code comments

### ISSUE THREAD

**Issue by m-brath** [atmtools/arts#533]
[ppath inline code comments](https://github.com/atmtools/arts/blob/7e2c9345fabd2e809e171c38119d42727d61aac8/src/ppath_struct.h#L17) are inconsistent. For example according to documentation `ppath.constant` is used only in 1D but it is also used in 2D and 3D. 

@erikssonpatrick : It would be nice if you can have a look on it.

**Comment by erikssonpatrick** [comment]
I noticed that you had fixed a bug about longitudes. Thanks. When it comes to the comment. Wrong of you have found that ppath.constant used in some way also for 2D and 3D. Feel free to remove the comment. 
Anyhow, I am a bit reluctant to spend time on the old code, to save it for my completely new version of ppath. In fact, I have got back to that the last weeks. Revised what I did last year and put it back in the present ARTS version. As well as some further development.
