### ISSUE TITLE
make pyarts did not work properly

### ISSUE THREAD

**Issue by mignonph75** [atmtools/arts#535]
**Describe the bug**

When executing arts-lectures/exercises/01-rotational_spectra/absorption.ipynb, I  get 
`RuntimeError: User Error: not std::filesystem::is_regular_file(path)`

In fact make pyarts did not work properly
kassad@GrandMagellan controlfiles % pwd;ls -la
/Users/kassad/Codes/arts/build/python/controlfiles
total 0
drwxr-xr-x   2 kassad  staff   64 25 sep 22:04 .
drwxr-xr-x  17 kassad  staff  544 28 sep 19:06 ..

**To Reproduce**
1. ... 
2. ...

If applicable, controlfile code:
```
Paste controlfile/python code here
```

If applicable, error output:
`Error is found at:
	/Users/kassad/Codes/arts/src/python_interface/py_agenda.cpp:38
Please follow these instructions to correct your error:
Cannot find file: "general/general.arts"
Search path:   . /Users/kassad/Codes/arts/controlfiles`
Paste terminal output here
```

**Expected behavior**
A clear and concise description of what you expected to happen.

/Users/kassad/Codes/arts/build/python/controlfiles filled with those files
    45 ws.execute_controlfile("general/general.arts")
     46 ws.execute_controlfile("general/continua.arts")
     47 ws.execute_controlfile("general/agendas.arts")

**System info (please complete the following information):**
 - OS: uname -a
Darwin GrandMagellan.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

 - Python Version
Python 3.9.6 (default, Aug  5 2022, 15:21:02) 
[Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Additional context**
Add any other context about the problem here.

**Thank you for helping me to fix this issue**

[build_arts.txt](https://github.com/atmtools/arts/files/9668300/build_arts.txt)
[cmake_arts.txt](https://github.com/atmtools/arts/files/9668301/cmake_arts.txt)
[make_arts.txt](https://github.com/atmtools/arts/files/9668302/make_arts.txt)

**Comment by olemke** [comment]
The arts-lectures package is not compatible with the latest master version of ARTS. Updated examples can be found in the [`arts/examples/classroom/`](https://github.com/atmtools/arts/tree/master/examples/classroom) folder.
