### ISSUE TITLE
ARTS spectral line catalogue

### ISSUE THREAD

**Issue by stefanbuehler** [atmtools/arts#57]
I think we should distribute spectral line catalogue data together with ARTS.

As baseline, perhaps two catalogues, the one by Agnes Perrin, to be used for planetary calculations up to 3THz. And one based on the latest HITRAN edition. (These two are already available, with the caveat that the HITRAN one is based on the 2012 version, so not exactly new.)

The format right now is ARTSCAT-5, but for the release it could be ARTSCAT-6, the version that is split by isotopologue and has all parameters that are common for the entire file at the beginning of the file.

There should be documentation of the format, perhaps best directly with the catalogue files (with a short note in the userguide that it can be found there)

I wonder whether subversion is the best system for such data. The current size of the split HITRAN catalogue is  200mb (each file is zipped). Subversion style version control does not seem to be terribly useful for this kind of data.

The goal is to have a simple short step-by-step list for new users to get up and running LBL calculations.

We could also consider Simon's suggestion to have a WSM that pulls the catalogue from an online location, storing a local cash. This could be done on the species (in ARTSCAT-6 isotopologue) level, then the individual files are quite small.

But if we start such a system, wouldn't it be tempting to do the same for other arts xml data?

**Comment by riclarsson** [comment]
We distribute my interpretation of HITRAN online in arts-xml-data.  Should we close this issue?  It seems to be a two-for-one kind of issue, where the distribution of the spectral catalog is separate from the automatic forward simulation data acquisition?

I am not sure that I like to have the data be automatically downloaded.  I like to have my local version.  I agree that subversion is not the best for these now quite large files.

**Comment by stefanbuehler** [comment]
Yes, let's close this issue. 

Future discussions are likely more about details, for example how to fix certain line parameters to other values, and which values to adopt.
