### ISSUE TITLE
Cached download system for arts-xml-data

### ISSUE THREAD

**Issue by stefanbuehler** [atmtools/arts#58]
Just a crazy idea, triggered by the line catalogue issue I juste created:

How about creating a local arts-xml-data folder during build and install, initially empty.

Then create new set of reading routines ReadArtsData(...).

They would look in the local arts-xml-data for the given file. If its there, they behave just like ReadXML. But if the file does not exist, they download it from the online master arts-xml-data location. (We could even think about a feature that checks if the online version is newer and re-downloads.)

I have no idea how easy it is to access the internet from within C++. It certainly opens a big (perhaps Pandoran) box. But if that is possible, the rest should be pretty simple, it seems to me.

**Comment by erikssonpatrick** [comment]
Don't know how complex this is to implement. If we go for this, we should also have scattering data in mind. These data are not in arts-xml-data. Simon has started something in this direction.
