### ISSUE TITLE
missing test functions 

### ISSUE THREAD

**Issue by nuitlejour** [atmtools/arts#669]
I am using the latest dev branch, during test time, about 1/3 of the tests failed, by examining detailed output information, some of test functions are missing, like:

test 15
        Start  15: converted.fast.artscomponents.helpers.TestForloop

15: Test command: /root/miniconda3/envs/pyarts-dev/bin/python3.10 "controlfiles/artscomponents/helpers/TestForloop.py"
15: Working Directory: /mnt/d/Work/Arts/arts/build/python
15: Environment variables: 
15:  PYTHONPATH=/mnt/d/Work/Arts/arts/build/python
15:  ARTS_HEADLESS=1
15:  ARTS_INCLUDE_PATH=/mnt/d/Work/Arts/arts/controlfiles/artscomponents/helpers:/mnt/d/Work/Arts/arts/controlfiles:/mnt/d/Work/Arts/arts-xml-data-snapshot-arts-2.5.8:/mnt/d/Work/Arts/arts-cat-data-snapshot-arts-2.5.8
15:  ARTS_XML_DATA_DIR=/mnt/d/Work/Arts/arts-xml-data-snapshot-arts-2.5.8
15:  ARTS_CAT_DATA_DIR=/mnt/d/Work/Arts/arts-cat-data-snapshot-arts-2.5.8
15: Test timeout computed to be: 10000000
15: /root/miniconda3/envs/pyarts-dev/bin/python3.10: can't open file '/mnt/d/Work/Arts/arts/build/python/controlfiles/artscomponents/helpers/TestForloop.py': [Errno 2] No such file or directory
  1/112 Test  #15: converted.fast.artscomponents.helpers.TestForloop ......................................***Failed    0.03 sec
/root/miniconda3/envs/pyarts-dev/bin/python3.10: can't open file '/mnt/d/Work/Arts/arts/build/python/controlfiles/artscomponents/helpers/TestForloop.py': [Errno 2] No such file or directory

please check.

**Comment by nuitlejour** [comment]
or simply because those *.py files are renamed or moved during development, and forgetting modifying the test suite?

**Comment by olemke** [comment]
Don't run `check-all` at the moment. Some tests are failing due to internal changes in ARTS. I'm cleaning them up for the next release. For the time being, stick to the `check` target.

**Comment by olemke** [comment]
All tests that are run by `check-all` are now fixed in PR #670. However, I could not reproduce the error you see with the TestForloop. How do you run the tests? I assume you run `ctest` directly instead of `make check-all`? That would explain why the files are missing. Only the make target triggers the conversion of the arts controlfiles to Python scripts.

**Comment by nuitlejour** [comment]
Thank you for your reply, I am running ctest directly as suggested in arts github page. 
Thank you for you your explaination, I will go on using arts without worrying about possible compilation errors.
