### ISSUE TITLE
some of the tests still failed with make check-all

### ISSUE THREAD

**Issue by nuitlejour** [atmtools/arts#671]
I have recompiled the source code including lastest merge #670, and executing 'make check-all'; there are some of tests still failing, 
There are three types of failed tests:
(1) missing control file 'planet_mars.arts', 'planet_jupiter.arts' ...
(2) 'Dynamic tables not yet supported with threads.'
(3) abs_xsec_agenda_checkedCalc is not a known workspace method.

maybe the corresponding xml-data needs to be updated?
the complete check output are as follows:

[check_results.txt](https://github.com/atmtools/arts/files/12605558/check_results.txt)

**Comment by olemke** [comment]
Thanks for the feedback. I think I missed fixing a couple of tests yesterday since I didn't have arts-xml-data in the path and therefore I didn't see those failures. Will fix them soon. :-)
