### ISSUE TITLE
Bug for Numeric

### ISSUE THREAD

**Issue by Shaofei-Wang224** [atmtools/arts#703]
Hi, all

when i use pyarts, function Numeric returns wrong results with the  data type float32.

The bug can be reproduce with the following code:

######
from pyarts.arts import Numeric
import numpy as np

array1 = np.array([1,2,3,4], dtype='float32')
a1 = np.mean(array1)
m1 = Numeric(np.mean(array1))
array2 = np.array([1,2,3,4], dtype='float64')
a2 = np.mean(array2)
m2 = Numeric(np.mean(array2))
######
The result is:
a1 = 2.5 and a2=2.5;
m1=2.0 and m2 =2.5.

arts version is 2.5.11
numpy version: 1.23.5

**Comment by olemke** [comment]
Thanks for the bug report. This is caused by how the automatic type conversion is currently handled and we aim for fixing that in the next release. In the meantime, as a workaround, you can also use `np.mean(array1, dtype=Numeric)`.
