### ISSUE TITLE
Remove old system for PSDs

### ISSUE THREAD

**Issue by erikssonpatrick** [atmtools/arts#87]
We have now two systems for describing PSDs. Only the new system supports retrievals and the old shall be removed. Things to be done:
- Clean up the code
- Remove or revise instructions in developer guide
- Revise or make new checks for scattering solvers

**Comment by erikssonpatrick** [comment]
@m-brath I assigned you and me to this issue. Did you see the email from Stuart? Having two systems cause confusion so would be good to attack this quite soon. Could you clean up the code? You know that part better than I do. A  problem here is that a number of tests use the old PSDs. My suggestion is to simply remove those tests, and instead make new ones. I could take on making (at least some) new tests. For example, we should have one or several tests checking the consistency between scattering solvers.

**Comment by m-brath** [comment]
Yes, I saw the email from Stuart. I can clean up the PSD system.

**Comment by erikssonpatrick** [comment]
@m-brath Now made some work on this issue. I will make another test for Hybrid at some point but asked for a pull request now to make my changes available for you. 
Note that I moved psdSeifertBeheng06 and psdMilbrandtYau05 to m_psd.cc. Could these methods be changed to use the general MGD functions, a bit similar to what Stuart did? I think I compared your methods with the MGD ones, and all looked OK. But not sure ...

**Comment by m-brath** [comment]
I worked on removing the old psd-scheme. I already deleted it, but I did not made a pull request, because the testcases still needed to be updated. Since you already did this with your last pull request, I think, I can do tomorrow the pull request.

Concerning psdSeifertBeheng06 and psdMilbrandtYau05, I think, they can be modified in that way.

**Comment by m-brath** [comment]
I removed pnd_fieldCalcFromscat_speciesFields and the depending functions. What about this dNdD_* workingspace methods, should they also be removed? My personal suggestion is too remove them, too.

**Comment by erikssonpatrick** [comment]
I see the dNdD methods as part of the old PSD system. So yes, they should be removed.

**Comment by erikssonpatrick** [comment]
Issue closed by accepted pull request #95
